FROM php:7.3-apache

COPY docker/php/vhost.conf /etc/apache2/sites-available/000-default.conf

COPY . /var/www/html

RUN rm -rf docker

RUN chown -R www-data:www-data /var/www/html \
    && a2enmod rewrite
